#  ascii.inc
#
#  ASCII constants
#
#  Paul Griffiths, November 7, 2015

.set    CHAR_NUL,       0x00            #  ASCII null character
.set    CHAR_BS,        0x08            #  ASCII backspace character
.set    CHAR_HTAB,      0x09            #  ASCII horizontal tab character
.set    CHAR_TAB,       0x09            #  ASCII horizontal tab character
.set    CHAR_LF,        0x0A            #  ASCII line feed character
.set    CHAR_VTAB,      0x0B            #  ASCII vertical tab character
.set    CHAR_FF,        0x0C            #  ASCII form feed character
.set    CHAR_CR,        0x0D            #  ASCII carriage return character
.set    CHAR_SPACE,     0x20            #  ASCII space character
.set    CHAR_ZERO,      0x30            #  ASCII code for '0'
.set    CHAR_NINE,      0x39            #  ASCII code for '9'
.set    CHAR_UPPER_A,   0x41            #  ASCII uppercase 'A'
.set    CHAR_UPPER_Z,   0x5A            #  ASCII uppercase 'Z'
.set    CHAR_LOWER_A,   0x61            #  ASCII lowercase 'a'
.set    CHAR_LOWER_Z,   0x7A            #  ASCII lowercase 'z'
